apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelx-config
  namespace: sentinelx-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_SERVER_URL: "http://eureka-service:8761/eureka"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MONGODB_URI: "mongodb://mongo-service:27017/sentinelx_fraud"
  NEO4J_URI: "bolt://neo4j-service:7687"
  OPENSEARCH_URL: "http://opensearch-service:9200"
  QDRANT_HOST: "qdrant-service"
  QDRANT_PORT: "6334"
  ML_SERVICE_URL: "http://ml-service:8000"
