apiVersion: v1
kind: Secret
metadata:
  name: sentinelx-secrets
  namespace: sentinelx-prod
type: Opaque
stringData:
  JWT_SECRET: "${ENV_JWT_SECRET}"
  MYSQL_ROOT_PASSWORD: "${ENV_MYSQL_ROOT_PASSWORD}"
  MYSQL_PASSWORD: "${ENV_MYSQL_PASSWORD}"
  EUREKA_SERVER_PASSWORD: "${ENV_EUREKA_SERVER_PASSWORD}"
