server:
  port: 8082

spring:
  application:
    name: wallet-service

  cloud:
    config:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/upi_wallet_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pop99558$$}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: WalletHikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:${REDIS_HOST:localhost}}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:${KAFKA_SERVERS:localhost:9092}}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_SERVER:http://admin:admin123@localhost:8761/eureka/}}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.upi.wallet: DEBUG